#define METATARSAL_1_THERMISTOR_ID 1
#define METATARSAL_5_THERMISTOR_ID 2
#define HALLUX_THERMISTOR_ID 3
#define CALCANEUS_THERMISTOR_ID 4

#define METATARSAL_1_FSR_ID 1
#define METATARSAL_2_FSR_ID 2

#define SPO2_ID 1