#define METATARSAL_1_THERMISTOR 1
#define METATARSAL_5_THERMISTOR 2
#define HEEL_THERMISTOR 3
#define BIG_TOE_THERMISTOR 4

#define METATARSAL_1_FSR 1
#define METATARSAL_5_FSR 2
#define HEEL_FSR 3
#define BIG_TOE_FSR 4

#define SPO2_ID 1